# 
# policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/g1/motion.pt"
#policy_path: "/home/furui/unitree_rl_gym/logs/g1/exported/policies/policy_gru.pt"
policy_path: "/home/furui/unitree_rl_gym/logs/g1/exported/policies/policy_lstm_1.pt"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/g1_description/scene.xml"

# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [100,100,100,150,40,40,100,100,100,150,40,40,100,50,50,50,50,30,50,50,50,50,30]
kds: [2, 2, 2, 4, 2, 2, 2, 2, 2, 4, 2, 2,2,2,2,2,2,2,2,2,2,2,2]

default_angles: [0.0,1.3,1.32,1.14,0.0,0.0,0.0,-1.31,-1.32,1.14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]
#default_angles: [-0.1,0,0.0,0.3,-0.2,-0.0, -0.1,0,0.0,0.3,-0.2,-0.0,0,0.3,0.3,0.0,0.0,0.0,0.3,-0.3,0.0,0.0,0.0]
#default_angles: [0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]
#default_angles: [1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 23
num_obs: 80

cmd_init: [0, 0, 0]
